---
- name: Check go-carbon is installed
  command: dpkg-query -f '${Status}' -W go-carbon
  check_mode: false
  register: go_carbon_installed
  failed_when: go_carbon_installed.rc not in [0, 1]
  changed_when: false

- block:
  - name: Download go-carbon deb package
    get_url:
      url: "https://github.com/go-graphite/go-carbon/releases/download/v{{ go_carbon_version }}/go-carbon_{{ go_carbon_version }}_amd64.deb"
      dest: "/tmp/go-carbon_{{ go_carbon_version }}_amd64.deb"

  - name: Install go-carbon
    command: dpkg -i /tmp/go-carbon_{{ go_carbon_version }}_amd64.deb

  when: go_carbon_installed.stdout != "install ok installed"
