---
- name: Check carbonapi is installed
  command: dpkg-query -f '${Status}' -W carbonapi
  check_mode: false
  register: carbonapi_installed
  failed_when: carbonapi_installed.rc not in [0, 1]
  changed_when: false

- block:
  - name: Download carbonapi deb package
    get_url:
      url: https://github.com/hnakamur/carbonapi-deb-docker/releases/download/{{ carbonapi_deb_version }}/carbonapi_{{ carbonapi_deb_version }}_amd64.deb    
      dest: "/tmp/carbonapi_{{ carbonapi_deb_version }}_amd64.deb"

  - name: Install carbonapi
    command: apt-get install -y /tmp/carbonapi_{{ carbonapi_deb_version }}_amd64.deb

  when: carbonapi_installed.stdout != "install ok installed"
